### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by ghost** [f-prime/zCoin#15]
Could you do releases, please? I don't want to have to update zCoin every commit. Thanks.

**Comment by f-prime** [comment]
Are you using zCoin now?

**Comment by ghost** [comment]
Uhh...no, not right now, but I am going to.

**Comment by f-prime** [comment]
I have fixed it, delete all your .db, pull zCoin, and restart it.

**Comment by ghost** [comment]
Thanks, but is there a release schedule?

**Comment by f-prime** [comment]
The current code is an official release as I do not plan on making any more
chances as of right now

**Comment by ghost** [comment]
Okay, because if you hit the "releases" button on the hotbar (or whatever you call it), you can make an official release.

**Comment by f-prime** [comment]
There we go

**Comment by ghost** [comment]
Thanks.
