### ISSUE TITLE
ip still usable?

### ISSUE THREAD

**Issue by ethsmith** [f-prime/zCoin#17]
this comes from the config.py is the ip ¨zcoin.zapto.org¨ still usable? Just wondering i may be misreading what that ip is used for lol

i can get the ip changed to zcoin.enterpriseservers.co pretty quick if needed

import landerdb

relay = 0
brokers = [{"ip":"zcoin.zapto.org", "port":6565}]
version = "0.2.1"
host = "0.0.0.0"
port = 6565
nodes = landerdb.Connect("nodes.db")
wallet = landerdb.Connect("wallet.db")
db = landerdb.Connect("db.db")

**Comment by alecnunn** [comment]
After almost a year, I doubt it.  Simply set up your own master node/broker and distribute it.

**Comment by ethsmith** [comment]
yeah i am trying to get zCoin out there again and thought i might ask him if thats even still being used :P

**Comment by ethsmith** [comment]
I have permission to bring back the zCoin network from the creator haha

**Comment by alecnunn** [comment]
It is open source, anybody can start up their own "zCoin network", but congratulations.

**Comment by ethsmith** [comment]
yes not saying it like that, im saying it like I have permission to change what i need, but i still want it to be the original zCoin network

**Comment by ethsmith** [comment]
so if that ip is still usuable i want to use it, but i will change it if needed

**Comment by ethsmith** [comment]
sorry for the confusion :P lol

**Comment by f-prime** [comment]
zcoin.zapto.org is the DNS I used for the god node. You can register that
domain again and point it where it needs to go. The more god nodes the
better as it prevents the system from being a client-server system and
makes it more p2p. If the god node goes down and there aren't others the
network won't accept any new nodes.

**Comment by f-prime** [comment]
Also, zapto.org is just no-ip

**Comment by ethsmith** [comment]
Ok thank you :)

**Comment by ethsmith** [comment]
I own a server hosting company, so might just make the DNS domains z1.enterpriseservers.co, z2.enterpriseservers.co, z3.enterpriseservers.co since that domain is my multipurpose domain haha

**Comment by f-prime** [comment]
Okay that's fine
